version: '3.3'

services:
    data2dto_php:
        image: dh.rinsvent.ru/php8dev
        container_name: data2dto_php
        volumes:
            - ./:/app
        environment:
            USE_COMPOSER_SCRIPTS: 1
            PHP_IDE_CONFIG: "serverName=data2dto_php"

networks:
    default:
        external:
            name: full-project
